### PR TITLE
SF4 + PHPUnit 6 Support

### PR DESCRIPTION
**Pull request by silverbackdan**
I've made some adjustments and all the tests are now passing using SF4. This includes:
- `Symfony\Component\DependencyInjection\DefinitionDecorator;` to `Symfony\Component\DependencyInjection\ChildDefinition;` (with support still for SF3)
- Making services public (they default to private in SF4)
- Extending the updated PHPUnit TestCase class
- Updating some tests to include the timeout parameter
- Using `getMockBuilder` and `getMock` instead of `createMock` in tests
- Adding phpunit as a dev dependency

As the check I have created for the DefinitionDecorator uses `::class` which is only supported in PHP 5.5+ I have increased that from PHP 5.3.2 - As far as I can tell this is the only breaking change. If you'd rather still support PHP 5.3.2 then feel free to adjust

Related ticket: https://github.com/doctrine/DoctrineCouchDBBundle/issues/58

### CODE REVIEW

**Comment by silverbackdan** [comment]
Also, is this needed?
https://github.com/doctrine/DoctrineCouchDBBundle/blob/7b1204c6655e607c7114e7cbfbf5de0f5d9ba93a/DoctrineCouchDBBundle.php#L46-L48

MongoDBBundle doesn't seem to have this anymore in that bundle's initialisation.

Happy to remove in this PR if it can be.

**Comment by silverbackdan** [comment]
As it stands, tests are passing on SF4 with no deprecation warnings either.

**Comment by founet** [comment]
I am very interrested by this pull request, can you please merge the pull request . Thanks

**Comment by kl3sk** [comment]
I'am interessted too. Any plan to merge ?

Edit:

I'll try your fork and doesn't seems to work, maybe i'dont use it correctly.

Please provide a SF4 compliant Readme

Edit2:
BTW, is this compatible with CouchDB 2.x ?

I have this error:

`
Attempted to call an undefined method named "setAllOrNothing" of class "Doctrine\CouchDB\Utils\BulkUpdater".
`

**Comment by jwage** [comment]
We don't currently have anyone working on maintaining the couchdb stuff in Doctrine. The people who built it initially and were maintaining it don't seem to be working on it anymore. Any volunteers to take it over?

**Comment by kl3sk** [comment]
Ho this sound bad, I really appreciate Doctrine and use it as an ORM, but now i would use it as an ODM.

Any chances that someone will work on it for CouchDb2 ?

Edit:
@silverbackdan seems te be interessted in. He has (here) a wating PR, maybe this could be a good start ?

**Comment by jwage** [comment]
We would need to make some updates to the project infrastructure and add travis-ci, scrutinizer, etc. in order to get this moving forward. I would do that in a separate PR first so that we know we're not introducing problems by merging this.

**Comment by kl3sk** [comment]
Ok this is very interessting, I'am very interrested in using Doctrine with CouchDB2 for a project.

Any Roadmap for this ?

**Comment by jwage** [comment]
Hi, as I mentioned previously, we don't have anyone working on these projects that I am aware of so we would need people to step up and start submitting pull requests to bring the projects up to speed with how other Doctrine projects are maintained.

- Add scrutinizer https://github.com/doctrine/migrations/blob/master/.scrutinizer.yml
- Add Travis-CI https://github.com/doctrine/migrations/blob/master/.travis.yml
- Add Doctrine Coding Standard 4.0 https://github.com/doctrine/migrations/blob/master/phpcs.xml.dist & https://github.com/doctrine/migrations/blob/master/composer.json#L23
- Add PHPStan https://github.com/doctrine/migrations/blob/master/phpstan.neon & https://github.com/doctrine/migrations/blob/master/composer.json#L27

I would be happy to guide someone and review pull requests and work with someone to make this happen.

**Comment by kl3sk** [comment]
Ok sorry, i understand that you migth want to reload/restart the project. I am not sure how i can really help you, because i don't really know those tools.

**Comment by silverbackdan** [comment]
Sorry for my delay in replying - I've been away.

> I'am interessted too. Any plan to merge ?
> 
> Edit:
> 
> I'll try your fork and doesn't seems to work, maybe i'dont use it correctly.
> 
> Please provide a SF4 compliant Readme
> 
> Edit2:
> BTW, is this compatible with CouchDB 2.x ?
> 
> I have this error:
> 
> Attempted to call an undefined method named "setAllOrNothing" of class "Doctrine\CouchDB\Utils\BulkUpdater".

@kl3sk - I am using this with CouchDB 2.1.1 - I'm not sure the error is related to this PR as I can't see any changes relating to calling the method 

> Edit:
> @silverbackdan seems te be interessted in. He has (here) a wating PR, maybe this could be a good start ?

@kl3sk - I'm afraid I don't think I'd have the time or the experience in maintaining a project of this size but I'm happy to contribute where I can to help OS projects continue to grow.

> Hi, as I mentioned previously, we don't have anyone working on these projects that I am aware of so we would need people to step up and start submitting pull requests to bring the projects up to speed with how other Doctrine projects are maintained.
> 
> Add scrutinizer https://github.com/doctrine/migrations/blob/master/.scrutinizer.yml
> Add Travis-CI https://github.com/doctrine/migrations/blob/master/.travis.yml
> Add Doctrine Coding Standard 4.0 https://github.com/doctrine/migrations/blob/master/phpcs.xml.dist & https://github.com/doctrine/migrations/blob/master/composer.json#L23
> Add PHPStan https://github.com/doctrine/migrations/blob/master/phpstan.neon & https://github.com/doctrine/migrations/blob/master/composer.json#L27
> I would be happy to guide someone and review pull requests and work with someone to make this happen.

@jwage - I am interested in helping with your suggestions. It's nice to have real examples that you've provided so I will try to make PRs during free time. I'd love it to be up to the same standard as the other Doctrine projects and hope to take this as a learning experience as well. Thanks for the summary of what needs to be done. I am familiar with all these tools/standards but will need to brush up I think so your guidance and review or PRs would be invaluable thank you.

Brining the conversation back to this PR - would this look to be merged once tests are passing and updates are completed assuming that this PR does not break any tests?

**Comment by itcreator** [comment]
> I'am interessted too. Any plan to merge ?
> 
> Edit:
> 
> I'll try your fork and doesn't seems to work, maybe i'dont use it correctly.
> 
> Please provide a SF4 compliant Readme
> 
> Edit2:
> BTW, is this compatible with CouchDB 2.x ?
> 
> I have this error:
> 
> Attempted to call an undefined method named "setAllOrNothing" of class "Doctrine\CouchDB\Utils\BulkUpdater".

I have this issue on master branch of bundle with out this changes (symfony 2.8)
looks like it is not a problem of this PR

**Comment by itcreator** [comment]
looks like it was affected by changes in **doctrine/couchdb-clien**
https://github.com/doctrine/couchdb-client/commit/0654638f7ee7320665b44647ba605cf03c7d84bd#diff-8fbc723a02110a9c131823e9de9006ec

**Comment by jwage** [comment]
> would this look to be merged once tests are passing and updates are completed assuming that this PR does not break any tests?

@silverbackda yes.

**Comment by kl3sk** [comment]
@jwage, just to be sure that @silverbackdan was pinged ;) (You've misspell his pseudo)

**Comment by silverbackdan** [comment]
Thanks both @jwage and @kl3sk 

I'm crazy busy at the moment but will look through this along with any other comments on OS projects as soon as I'm able.

If there is an urgent need for this to be merged I'm more than happy for someone else to make the changes. Just ping me here and link to the other PR so we can link the 2.

I'll do what I can though.

Cheers!

**Comment by silverbackdan** [comment]
Hi all, sorry I forgot about this. My branch is still there if anyone finds this and wants to take over the PR. I think as it's so old now it's prudent for me just to close this as I haven't had time and don't see myself having time for this. Sorry!

**Pull request closed without merging**
